name: build
on:
  push:
    branches:
      - development
jobs:
  build-android-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: |
          yarn install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload release build
        uses: JantHsueh/upload-file-action@master
        with:
          url: "http://baed4ff.online-server.cloud:8081/bot${{secrets.bot_key}}/sendDocument"
          forms: '{"chat_id": ${{secrets.chat_id}}, "caption": "A new DevLights mobile app release build for Android is ready. Try it out now!"}'
          fileForms: '{"document": "android/app/build/outputs/apk/release/app-release.apk"}'
  build-android-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: |
          yarn install
      - name: Build Android Debug
        run: |
          cd android && ./gradlew assembleDebug
      - name: Upload release build
        uses: JantHsueh/upload-file-action@master
        with:
          url: "http://baed4ff.online-server.cloud:8081/bot${{secrets.bot_key}}/sendDocument"
          forms: '{"chat_id": ${{secrets.chat_id}}, "caption": "A new DevLights mobile app debug build for Android is ready. Try it out now!"}'
          fileForms: '{"document": "android/app/build/outputs/apk/debug/app-debug.apk"}'
